import {
  faCaretDown,
  faAngleRight,
  faCaretRight,
  faFolder,
  faEye,
  faEyeSlash,
  faFile,
  faBookmark,
  faEllipsisVertical,
  faDownload,
  faPlus,
  faMinus,
  faXmark,
  faFileArrowUp,
  faChevronDown,
  faMagnifyingGlass,
  faShare,
  faTrashCan,
  faAngleLeft,
  faAngleDown,
  faCamera,
  faLink,
  faCircleCheck,
  faRightFromBracket,
  faPencil,
  faUpload,
  faUser,
  faGear,
  faGripLinesVertical,
  faBell,
  faFolderTree,
} from '@fortawesome/free-solid-svg-icons';

const icon = {
  caretDown: faCaretDown,
  caretRight: faCaretRight,
  camera: faCamera,
  angleRight: faAngleRight,
  angleLeft: faAngleLeft,
  angleDown: faAngleDown,
  folder: faFolder,
  eye: faEye,
  eyeSlash: faEyeSlash,
  file: faFile,
  bookMark: faBookmark,
  ellipsisVertical: faEllipsisVertical,
  download: faDownload,
  plus: faPlus,
  minus: faMinus,
  xmark: faXmark,
  fileArrowUp: faFileArrowUp,
  chevronDown: faChevronDown,
  magnifyingGlass: faMagnifyingGlass,
  share: faShare,
  trashCan: faTrashCan,
  link: faLink,
  circleCheck: faCircleCheck,
  rightFromBracket: faRightFromBracket,
  pencil: faPencil,
  upload: faUpload,
  user: faUser,
  gear: faGear,
  gripLinesVertical: faGripLinesVertical,
  bell: faBell,
  folderTree: faFolderTree,
};

export default icon;
